### ISSUE TITLE
dead link in documentation

### ISSUE THREAD

**Issue by Segaja** [vcs-python/vcspull#345]
https://github.com/vcs-python/vcspull/blob/master/docs/config-generation.md?plain=1#L112

The link in this line leads me to a "404 Not Found"

**Comment by tony** [comment]
@Segaja Try now, better?

**Comment by Segaja** [comment]
Now it works. So you have to add new people to the feature, or did you now just open it up for all?

**Comment by tony** [comment]
I had to turn it on by making an initial post, apparently

**Comment by Segaja** [comment]
perfect ;)
