### ISSUE TITLE
Bump minimum python version

### ISSUE THREAD

**Issue by tony** [vcs-python/vcspull#355]
[Python 3.9](https://docs.python.org/3/whatsnew/3.9.html) benefits vcspull and libvcs could use:
- [`typing.TypedDict`](https://docs.python.org/3/library/typing.html#typing.TypedDict) as of 3.8 (no need for backport package)
- [`typing.Protocol`](https://docs.python.org/3/library/typing.html#typing.Protocol)
- [`typing.Literal`](https://docs.python.org/3/library/typing.html#typing.Literal)
- Typing syntax improvements: `List[str]` -> `list[str]` ([Type Hinting Generics in Standard Collections](https://docs.python.org/3/whatsnew/3.9.html#type-hinting-generics-in-standard-collections))

## Analysis of distros

- Debian python 3.9
 
  > Bullseye is the codename for Debian 11, released on 2021-08-14.
  > https://wiki.debian.org/DebianBullseye
  > Python 3, 3.9.1
- RedHat RHEL uses 3.6 by default, has up to 3.9
  > You can install Python 3.8 and Python 3.9, including packages built for either version, in parallel with Python 3.6 on the same system, with the exception of the mod_wsgi module. Due to a limitation of the Apache HTTP Server, only one of the python3-mod_wsgi, python38-mod_wsgi, or python39-mod_wsgi packages can be installed on a system.
  > [source](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/configuring_basic_system_settings/assembly_installing-and-using-python_configuring-basic-system-settings)

**Comment by tony** [comment]
@Segaja @rogerioefonseca Do you have a minimum python version you can handle? (if you're still around)  you're the most communicable here of the now

I want to make 3.9 the minimum, would that impact your ability to use the package?

**Comment by rogerioefonseca** [comment]
Hey there, I'm using python 3.9 for a while already, so no harm for me.

**Comment by tony** [comment]
Thank you!  I am looking to bump versions across all projects.

**Comment by tony** [comment]
Dropped 3.7 and 3.8 https://github.com/vcs-python/vcspull/pull/356  https://github.com/vcs-python/libvcs/pull/308

Anything available in standard library in 3.9 is available

**Comment by tony** [comment]
I will close this for now! Thank you!
